import React, { useRef } from 'react';
import { useAuth } from '../context/AuthContext';
import { useReport, ReportData } from '../hooks/useReport';

// ─── Severity colours ─────────────────────────────────────────────────────────
const SEV_COLOR: Record<string, string> = {
  critical: 'bg-red-50 text-red-700 border-red-200',
  high:     'bg-orange-50 text-orange-700 border-orange-200',
  medium:   'bg-amber-50 text-amber-700 border-amber-200',
  low:      'bg-emerald-50 text-emerald-700 border-emerald-200',
};
const SEV_DOT: Record<string, string> = {
  critical: 'bg-red-500', high: 'bg-orange-500', medium: 'bg-amber-500', low: 'bg-emerald-500',
};
const PRIORITY_COLOR = SEV_COLOR;

// ─── Framework badge colours ───────────────────────────────────────────────────
const FW_COLORS = [
  'bg-blue-50 text-blue-700 border-blue-200',
  'bg-purple-50 text-purple-700 border-purple-200',
  'bg-indigo-50 text-indigo-700 border-indigo-200',
  'bg-teal-50 text-teal-700 border-teal-200',
  'bg-cyan-50 text-cyan-700 border-cyan-200',
  'bg-violet-50 text-violet-700 border-violet-200',
  'bg-sky-50 text-sky-700 border-sky-200',
];

// ─── Reusable KPI tile ────────────────────────────────────────────────────────
const KpiTile: React.FC<{
  label: string; value: string | number; icon: string; color: string; sub?: string;
}> = ({ label, value, icon, color, sub }) => (
  <div className="bg-white rounded-2xl border border-slate-200 p-4 flex flex-col gap-2 shadow-xs hover:shadow-md transition-all">
    <div className="flex items-center justify-between">
      <span className="text-[10px] font-bold uppercase tracking-widest text-slate-500">{label}</span>
      <span className={`material-symbols-outlined text-lg ${color}`}>{icon}</span>
    </div>
    <div className={`text-2xl font-extrabold ${color} leading-none`}>{value}</div>
    {sub && <p className="text-[10px] text-slate-400 font-mono mt-0.5">{sub}</p>}
  </div>
);

// ─── Section header ───────────────────────────────────────────────────────────
const SectionHeader: React.FC<{ icon: string; title: string; badge?: string }> = ({ icon, title, badge }) => (
  <div className="flex items-center gap-3 mb-4 pb-2 border-b border-slate-200">
    <span className="material-symbols-outlined text-blue-600 text-xl">{icon}</span>
    <h3 className="text-base font-bold text-slate-900">{title}</h3>
    {badge && (
      <span className="ml-auto text-[10px] font-bold uppercase tracking-wider text-blue-700 bg-blue-50 px-2 py-0.5 rounded border border-blue-200">
        {badge}
      </span>
    )}
  </div>
);

// ─── Full Report Render ───────────────────────────────────────────────────────
const FullReport: React.FC<{ report: ReportData; user: { name?: string; email?: string; role?: string } }> = ({ report, user }) => {
  const now = new Date(report.generatedAt);
  const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', second: '2-digit' });

  return (
    <div id="audit-report-content" className="space-y-8 text-slate-900">

      {/* ── REPORT HEADER ───────────────────────────────────────────────────── */}
      <div className="bg-gradient-to-br from-slate-900 via-blue-950 to-slate-900 rounded-3xl p-8 text-white shadow-2xl print:rounded-none">
        <div className="flex flex-col md:flex-row items-start md:items-center gap-6">
          <div className="w-14 h-14 rounded-2xl bg-white/10 backdrop-blur-sm border border-white/20 flex items-center justify-center shadow-lg">
            <span className="material-symbols-outlined text-white text-3xl">shield_with_heart</span>
          </div>
          <div className="flex-1">
            <p className="text-blue-300 text-[10px] font-bold uppercase tracking-widest mb-1">Enterprise AI Compliance Engine</p>
            <h1 className="text-2xl md:text-3xl font-extrabold leading-tight">Compliance Audit Report</h1>
            <p className="text-slate-300 text-sm mt-1">Comprehensive Knowledge Graph–Driven Security & Regulatory Assessment</p>
          </div>
          <div className="text-right text-sm space-y-1">
            <p className="text-blue-200 font-mono text-xs">{dateStr}</p>
            <p className="text-slate-400 font-mono text-xs">{timeStr}</p>
            <span className="inline-block text-[10px] font-bold uppercase tracking-wider bg-emerald-500/20 text-emerald-300 px-2 py-0.5 rounded border border-emerald-500/30 mt-1">
              LIVE DATA
            </span>
          </div>
        </div>

        {/* Meta strip */}
        <div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-4 pt-4 border-t border-white/10">
          {[
            { label: 'Generated By', value: user.name || user.email || 'Authenticated User' },
            { label: 'Role', value: (user.role || 'ADMIN').replace('_', ' ') },
            { label: 'Frameworks Detected', value: report.detectedFrameworks.length.toString() || 'Analyzing...' },
            { label: 'Report Type', value: 'Full Audit' },
          ].map(item => (
            <div key={item.label}>
              <p className="text-[10px] text-slate-400 uppercase tracking-widest mb-0.5">{item.label}</p>
              <p className="text-sm font-bold text-white">{item.value}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── VALIDATION BANNER ───────────────────────────────────────────────── */}
      {!report.validationPassed ? (
        <div className="bg-amber-50 border border-amber-300 rounded-2xl p-4 flex items-start gap-3">
          <span className="material-symbols-outlined text-amber-600 text-xl mt-0.5">warning</span>
          <div>
            <p className="font-bold text-amber-800 text-sm">Data Validation Warning</p>
            <ul className="mt-1 space-y-0.5">
              {report.validationNotes.map((n, i) => (
                <li key={i} className="text-xs text-amber-700">• {n}</li>
              ))}
            </ul>
          </div>
        </div>
      ) : (
        <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-3 flex items-center gap-3">
          <span className="material-symbols-outlined text-emerald-600">check_circle</span>
          <p className="text-sm font-semibold text-emerald-800">Data validation passed — all report values are sourced from live backend data.</p>
        </div>
      )}

      {/* ── SYSTEM OVERVIEW KPIs ────────────────────────────────────────────── */}
      <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">
        <SectionHeader icon="monitoring" title="System Overview" badge="Live" />
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <KpiTile label="Total Documents" value={report.totalDocuments} icon="description" color="text-blue-600" sub="Uploaded to system" />
          <KpiTile label="Processed" value={report.processedDocuments} icon="task_alt" color="text-emerald-600" sub="Successfully ingested" />
          <KpiTile label="Risk Flagged" value={report.failedDocuments} icon="flag" color="text-orange-500" sub="Require review" />
          <KpiTile label="Avg Confidence" value={`${report.avgConfidence}%`} icon="verified" color="text-indigo-600" sub="Entity extraction score" />
          <KpiTile label="Neo4j Entities" value={report.neo4jNodes.toLocaleString()} icon="account_tree" color="text-purple-600" sub="Graph nodes" />
          <KpiTile label="Relationships" value={report.neo4jRelationships.toLocaleString()} icon="share" color="text-blue-500" sub="Graph edges" />
          <KpiTile label="Qdrant Vectors" value={report.qdrantVectorCount.toLocaleString()} icon="auto_awesome" color="text-violet-600" sub="Semantic embeddings" />
          <KpiTile label="Graph Density" value={report.graphDensity.toFixed(4)} icon="bubble_chart" color="text-teal-600" sub="Neo4j edge ratio" />
          <KpiTile label="Avg Degree" value={`${report.avgDegree.toFixed(2)} edges/node`} icon="hub" color="text-blue-600" sub="Connectivity index" />
          <KpiTile label="Frameworks" value={report.detectedFrameworks.length} icon="policy" color="text-rose-600" sub="Detected in documents" />
          <KpiTile label="Entity Types" value={Object.keys(report.entityTypeDistribution).length} icon="category" color="text-amber-600" sub="Distinct node types" />
          <KpiTile label="LLM Provider" value={report.llmProvider} icon="smart_toy" color="text-slate-600" sub={`Model: ${report.embeddingModel}`} />
        </div>
      </div>

      {/* ── EXECUTIVE SUMMARY ───────────────────────────────────────────────── */}
      {report.executiveSummary && (
        <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">
          <SectionHeader icon="summarize" title="AI-Generated Executive Summary" badge="Graph RAG" />
          <p className="text-sm text-slate-700 leading-relaxed whitespace-pre-line">{report.executiveSummary}</p>
        </div>
      )}

      {/* ── FRAMEWORK COVERAGE ──────────────────────────────────────────────── */}
      {report.detectedFrameworks.length > 0 && (
        <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">
          <SectionHeader icon="policy" title="Detected Compliance Frameworks" badge={`${report.detectedFrameworks.length} found`} />
          <div className="flex flex-wrap gap-3">
            {report.detectedFrameworks.map((fw, i) => (
              <div key={fw} className={`flex items-center gap-2 px-4 py-2.5 rounded-xl border text-sm font-bold ${FW_COLORS[i % FW_COLORS.length]}`}>
                <span className="material-symbols-outlined text-base">verified_user</span>
                {fw}
              </div>
            ))}
          </div>
          <p className="text-xs text-slate-400 mt-3">
            Frameworks automatically detected by analyzing uploaded document names, content keywords, and extracted entity types in Neo4j.
          </p>
        </div>
      )}

      {/* ── ENTITY TYPE BREAKDOWN ───────────────────────────────────────────── */}
      {Object.keys(report.entityTypeDistribution).length > 0 && (
        <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">
          <SectionHeader icon="category" title="Entity Type Distribution" badge="Neo4j" />
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {Object.entries(report.entityTypeDistribution)
              .sort(([, a], [, b]) => (b as number) - (a as number))
              .map(([type, count]) => {
                const total = (Object.values(report.entityTypeDistribution) as number[]).reduce((s: number, v: number) => s + v, 0);
                const pct = total > 0 ? Math.round((Number(count) / total) * 100) : 0;
                return (
                  <div key={type} className="bg-slate-50 rounded-xl border border-slate-200 p-3">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs font-bold text-slate-900">{type}</span>
                      <span className="text-xs font-mono font-bold text-blue-600">{count.toLocaleString()}</span>
                    </div>
                    <div className="w-full h-1.5 bg-slate-200 rounded-full overflow-hidden">
                      <div className="h-full bg-blue-500 rounded-full" style={{ width: `${pct}%` }} />
                    </div>
                    <p className="text-[10px] text-slate-400 mt-1">{pct}% of all entities</p>
                  </div>
                );
              })}
          </div>
        </div>
      )}

      {/* ── TOP ENTITIES ────────────────────────────────────────────────────── */}
      {report.topEntities.length > 0 && (
        <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">
          <SectionHeader icon="star" title="Most Connected Entities" badge="Neo4j Centrality" />
          <div className="space-y-2">
            {report.topEntities.slice(0, 10).map((ent, i) => {
              const name = ent.name || ent.label || `Entity ${i + 1}`;
              const degree = ent.degree ?? 0;
              const maxDeg = report.topEntities[0]?.degree ?? 1;
              const pct = maxDeg > 0 ? Math.round((degree / maxDeg) * 100) : 0;
              return (
                <div key={i} className="flex items-center gap-3 p-2.5 rounded-xl hover:bg-slate-50 transition-colors">
                  <span className="text-[10px] font-bold text-slate-400 w-4 text-center">{i + 1}</span>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-xs font-semibold text-slate-800 truncate">{name}</span>
                      <span className="text-[10px] font-mono text-slate-500 ml-2">{degree} edges</span>
                    </div>
                    <div className="w-full h-1 bg-slate-200 rounded-full overflow-hidden">
                      <div className="h-full bg-purple-500 rounded-full" style={{ width: `${pct}%` }} />
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ── AI FINDINGS ─────────────────────────────────────────────────────── */}
      {report.aiFindings.length > 0 && (
        <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">
          <SectionHeader icon="security" title="AI Compliance Findings" badge="Graph RAG" />
          <div className="space-y-4">
            {report.aiFindings.map((finding, i) => (
              <div key={i} className={`p-4 rounded-xl border ${SEV_COLOR[finding.severity]}`}>
                <div className="flex items-start gap-3">
                  <div className={`w-2 h-2 rounded-full mt-1.5 flex-shrink-0 ${SEV_DOT[finding.severity]}`} />
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      <span className="text-sm font-bold">{finding.title}</span>
                      <span className={`text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded border ${SEV_COLOR[finding.severity]}`}>
                        {finding.severity}
                      </span>
                    </div>
                    <p className="text-xs leading-relaxed opacity-90">{finding.description}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── RECOMMENDATIONS ─────────────────────────────────────────────────── */}
      {report.recommendations.length > 0 && (
        <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">
          <SectionHeader icon="lightbulb" title="Actionable Recommendations" badge="With Citations" />
          <div className="space-y-4">
            {report.recommendations.map((rec, i) => (
              <div key={i} className="bg-slate-50 rounded-2xl border border-slate-200 p-4">
                <div className="flex items-start gap-3">
                  <div className={`px-2 py-0.5 rounded text-[9px] font-bold uppercase tracking-wider border flex-shrink-0 mt-0.5 ${PRIORITY_COLOR[rec.priority]}`}>
                    {rec.priority}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-bold text-slate-900 mb-1">{rec.title}</p>
                    <p className="text-xs text-slate-600 leading-relaxed mb-2">{rec.reason}</p>
                    {rec.citations.length > 0 && (
                      <div className="space-y-1">
                        {rec.citations.map((cite, ci) => (
                          <div key={ci} className="flex items-start gap-1.5 text-[10px] text-slate-500 bg-white border border-slate-200 rounded-lg px-2 py-1 font-mono">
                            <span className="material-symbols-outlined text-[12px] text-blue-500 mt-0.5">bookmark</span>
                            <span className="break-all">{cite}</span>
                          </div>
                        ))}
                      </div>
                    )}
                    {rec.framework && (
                      <span className="inline-block mt-2 text-[9px] font-bold uppercase tracking-wider text-indigo-700 bg-indigo-50 border border-indigo-200 px-2 py-0.5 rounded">
                        {rec.framework}
                      </span>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── DOCUMENT INVENTORY ──────────────────────────────────────────────── */}
      {report.documents.length > 0 && (
        <div className="bg-white rounded-3xl border border-slate-200 p-6 shadow-xs">
          <SectionHeader icon="folder_open" title="Document Inventory" badge={`${report.documents.length} files`} />
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-slate-200">
                  {['Document Name', 'Type', 'Framework', 'Entities', 'Confidence', 'Status'].map(h => (
                    <th key={h} className="text-left font-bold text-slate-500 uppercase tracking-wider pb-2 pr-4 text-[10px]">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {report.documents.map(doc => (
                  <tr key={doc.id} className="hover:bg-slate-50 transition-colors">
                    <td className="py-2 pr-4 font-medium text-slate-800 max-w-xs truncate">{doc.name}</td>
                    <td className="py-2 pr-4 text-slate-500 uppercase">{doc.type}</td>
                    <td className="py-2 pr-4 text-slate-600">{doc.framework || '—'}</td>
                    <td className="py-2 pr-4 font-mono">{doc.entities?.length ?? 0}</td>
                    <td className="py-2 pr-4">
                      <span className={`font-bold ${doc.confidence >= 90 ? 'text-emerald-600' : doc.confidence >= 75 ? 'text-amber-600' : 'text-red-500'}`}>
                        {doc.confidence}%
                      </span>
                    </td>
                    <td className="py-2">
                      <span className={`px-2 py-0.5 rounded text-[9px] font-bold border ${
                        doc.status === 'Compliant' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' :
                        doc.status === 'Risk Flagged' ? 'bg-red-50 text-red-700 border-red-200' :
                        'bg-amber-50 text-amber-700 border-amber-200'
                      }`}>{doc.status}</span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* ── REPORT FOOTER ───────────────────────────────────────────────────── */}
      <div className="bg-slate-900 rounded-3xl p-6 text-white print:rounded-none">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <p className="text-xs font-bold text-slate-300">Generated by Enterprise AI Compliance Engine</p>
            <p className="text-[10px] text-slate-500 mt-1">
              Powered by FastAPI · Neo4j · Qdrant · LangGraph · {report.llmProvider}
            </p>
            <p className="text-[10px] text-slate-500">
              Embedding model: {report.embeddingModel}
            </p>
          </div>
          <div className="text-right">
            <p className="text-[10px] text-slate-400 font-mono">{dateStr} {timeStr}</p>
            <p className="text-[10px] text-slate-500 mt-0.5">
              {report.totalDocuments} docs · {report.neo4jNodes} entities · {report.neo4jRelationships} relationships
            </p>
            <div className="flex items-center gap-1 mt-1 justify-end">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
              <span className="text-[10px] text-emerald-400 font-bold">Live Data Report</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// ─── Main ReportsView ─────────────────────────────────────────────────────────
export const ReportsView: React.FC = () => {
  const { user, activeRole } = useAuth();
  const { reportData, isGenerating, error, generate, reset } = useReport();

  const handlePrint = () => window.print();

  return (
    <div className="space-y-6 animate-in fade-in">

      {/* Print styles */}
      <style>{`
        @media print {
          body > * { display: none !important; }
          #audit-report-wrapper { display: block !important; position: static !important; }
          #audit-report-wrapper .no-print { display: none !important; }
          .print\\:rounded-none { border-radius: 0 !important; }
        }
      `}</style>

      {/* ── Header bar ────────────────────────────────────────────────────── */}
      <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs flex flex-col md:flex-row justify-between items-start md:items-center gap-4 no-print">
        <div>
          <h2 className="text-xl font-bold text-slate-900">Compliance Audit Reports</h2>
          <p className="text-xs text-slate-500 mt-1">
            Enterprise-grade audit report generated from live Neo4j, Qdrant, and AI pipeline data. No placeholder values.
          </p>
        </div>
        <div className="flex items-center gap-3 flex-wrap">
          {reportData && (
            <>
              <button
                onClick={reset}
                className="px-4 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold text-xs flex items-center gap-2 transition-all cursor-pointer"
              >
                <span className="material-symbols-outlined text-base">refresh</span>
                Regenerate
              </button>
              <button
                onClick={handlePrint}
                className="px-4 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-semibold text-xs flex items-center gap-2 transition-all cursor-pointer shadow-sm"
              >
                <span className="material-symbols-outlined text-base">print</span>
                Print / Export PDF
              </button>
            </>
          )}
          {!reportData && (
            <span className="text-xs font-bold text-emerald-700 bg-emerald-50 px-3 py-1.5 rounded-xl border border-emerald-200 uppercase tracking-wider">
              Live Data Only
            </span>
          )}
        </div>
      </div>

      {/* ── Generate Panel (initial state) ────────────────────────────────── */}
      {!reportData && !isGenerating && (
        <div className="bg-white rounded-3xl border border-slate-200 p-12 flex flex-col items-center text-center gap-6 shadow-xs no-print">
          <div className="w-20 h-20 rounded-3xl bg-blue-50 border border-blue-200 flex items-center justify-center">
            <span className="material-symbols-outlined text-blue-600 text-4xl">shield_with_heart</span>
          </div>
          <div>
            <h3 className="text-xl font-bold text-slate-900 mb-2">Generate Live Audit Report</h3>
            <p className="text-sm text-slate-500 max-w-md">
              This report is assembled entirely from your uploaded documents, Neo4j knowledge graph, Qdrant vector store,
              and AI pipeline in real time. No demo or placeholder data.
            </p>
          </div>

          {/* Data source indicators */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 w-full max-w-2xl">
            {[
              { label: 'Neo4j Graph', icon: 'account_tree', color: 'text-purple-600 bg-purple-50 border-purple-200' },
              { label: 'Qdrant Vectors', icon: 'auto_awesome', color: 'text-violet-600 bg-violet-50 border-violet-200' },
              { label: 'Documents', icon: 'description', color: 'text-blue-600 bg-blue-50 border-blue-200' },
              { label: 'Graph RAG AI', icon: 'smart_toy', color: 'text-emerald-600 bg-emerald-50 border-emerald-200' },
            ].map(src => (
              <div key={src.label} className={`flex flex-col items-center gap-1.5 p-3 rounded-xl border text-xs font-semibold ${src.color}`}>
                <span className="material-symbols-outlined text-xl">{src.icon}</span>
                {src.label}
              </div>
            ))}
          </div>

          <button
            id="generate-audit-report-btn"
            onClick={generate}
            className="px-8 py-3.5 bg-blue-600 hover:bg-blue-700 active:scale-95 text-white font-bold rounded-2xl flex items-center gap-3 shadow-lg shadow-blue-600/25 transition-all cursor-pointer text-sm"
          >
            <span className="material-symbols-outlined text-xl">auto_awesome</span>
            Generate Live Audit Report
          </button>
          <p className="text-[10px] text-slate-400">
            Generation takes 10–30 seconds depending on document volume and AI response time.
          </p>
        </div>
      )}

      {/* ── Generating State ───────────────────────────────────────────────── */}
      {isGenerating && (
        <div className="bg-white rounded-3xl border border-slate-200 p-12 flex flex-col items-center gap-6 shadow-xs no-print">
          <div className="relative">
            <div className="w-16 h-16 rounded-2xl bg-blue-600 flex items-center justify-center">
              <span className="material-symbols-outlined text-white text-3xl animate-spin">autorenew</span>
            </div>
            <div className="absolute -top-1 -right-1 w-4 h-4 rounded-full bg-emerald-500 animate-ping" />
          </div>
          <div className="text-center">
            <p className="font-bold text-slate-900 text-lg">Generating Enterprise Audit Report</p>
            <p className="text-sm text-slate-500 mt-1">Querying Neo4j · Qdrant · Graph RAG AI engine...</p>
          </div>
          <div className="w-full max-w-sm space-y-2">
            {[
              'Fetching graph statistics from Neo4j...',
              'Loading document inventory...',
              'Retrieving Qdrant vector count...',
              'Running AI analysis via Graph RAG...',
              'Generating executive summary...',
            ].map((step, i) => (
              <div key={i} className="flex items-center gap-2 text-xs text-slate-600">
                <span className="material-symbols-outlined text-sm text-blue-500 animate-spin" style={{ animationDelay: `${i * 0.2}s` }}>
                  progress_activity
                </span>
                {step}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Error State ────────────────────────────────────────────────────── */}
      {error && !isGenerating && (
        <div className="bg-red-50 rounded-2xl border border-red-200 p-6 flex items-start gap-4 no-print">
          <span className="material-symbols-outlined text-red-500 text-2xl">error</span>
          <div>
            <p className="font-bold text-red-800">Report Generation Failed</p>
            <p className="text-sm text-red-700 mt-1">{error}</p>
            <button
              onClick={generate}
              className="mt-3 px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-xs font-bold rounded-xl cursor-pointer transition-all"
            >
              Retry
            </button>
          </div>
        </div>
      )}

      {/* ── Full Report ────────────────────────────────────────────────────── */}
      {reportData && !isGenerating && (
        <div id="audit-report-wrapper">
          <FullReport
            report={reportData}
            user={{
              name: user?.name,
              email: user?.email,
              role: activeRole,
            }}
          />
        </div>
      )}
    </div>
  );
};
